// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiXBHltbRJhub0ysN3Z5XS-JEZIfLx-G4',
    appId: '1:338295389405:web:f02a2323d4a773c7e12f34',
    messagingSenderId: '338295389405',
    projectId: 'wikibus-7ac7e',
    authDomain: 'wikibus-7ac7e.firebaseapp.com',
    storageBucket: 'wikibus-7ac7e.appspot.com',
    measurementId: 'G-2NTDZSSQS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD28c3SlVJCkxUQ13L5L_Smm2YahYpTN4Q',
    appId: '1:338295389405:android:eaf84f6c6c976d31e12f34',
    messagingSenderId: '338295389405',
    projectId: 'wikibus-7ac7e',
    storageBucket: 'wikibus-7ac7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9TJBgnuftSyJPsgCUNNGia9ZaDg9koA',
    appId: '1:338295389405:ios:726992dba1ee1c1ee12f34',
    messagingSenderId: '338295389405',
    projectId: 'wikibus-7ac7e',
    storageBucket: 'wikibus-7ac7e.appspot.com',
    iosClientId: '338295389405-0clc4onrm553f9ih5bu18s0i6pij8p0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9TJBgnuftSyJPsgCUNNGia9ZaDg9koA',
    appId: '1:338295389405:ios:726992dba1ee1c1ee12f34',
    messagingSenderId: '338295389405',
    projectId: 'wikibus-7ac7e',
    storageBucket: 'wikibus-7ac7e.appspot.com',
    iosClientId: '338295389405-0clc4onrm553f9ih5bu18s0i6pij8p0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybus',
  );
}
